version: '3.8'

networks:
  my_network: {}

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my_network

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: trip_planner
    volumes:
      - postgres-data:/etc/postgresql/16/main/
      - ./src/main/resources/create.sql:/docker-entrypoint-initdb.d/create.sql
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - my_network

volumes:
  postgres-data:
